// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sequence

import (
	"github.com/depender/email-sequence-service/internal/sequence"
	"github.com/depender/email-sequence-service/internal/sequence/services"
	"github.com/depender/email-sequence-service/pkg/db"
)

// Injectors from wire.go:

func SequenceWire(db2 *db.Db) *Controller {
	repository := sequence.NewRepository(db2)
	service := services.NewService(repository)
	controller := NewController(service)
	return controller
}
